added utils in k8s-1-16
Signed-off-by: somesh kumar <somesh.kumar@mayadata.io>

diff --git a/script/utils/litmus_job_runner b/script/utils/litmus_job_runner
--- a/script/utils/litmus_job_runner
+++ b/script/utils/litmus_job_runner
@@ -11,13 +11,19 @@ jobNameCmd="kubectl get jobs -n litmus --no-headers -o jsonpath='{.items[?(@.met
 
 job_deploy_out=$(kubectl create -f ${litmus_job_file}) && \
 job_name=$(eval ${jobNameCmd}); retcode=$?
-${utils_path}/error_handler ${retcode} msg="Unable to run litmusbook, exiting" action="exit"
+
+while [ -z "$job_name" ]; do
+  sleep 5
+  job_name=$(eval ${jobNameCmd});
+done
+chmod 755 ../Openshift-EE/utils/error_handler
+bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to run litmusbook, exiting" action="exit"
 
 ## Obtain the litmus pod name 
 
 litmusPodCmd="kubectl get pod --no-headers -n litmus -o jsonpath='{.items[?(@.metadata.labels.job-name==\"${job_name}\")].metadata.name}'"
 litmus_pod=$(eval ${litmusPodCmd}); retcode=$?
-${utils_path}/error_handler ${retcode} msg="Unable to find litmus test runner pod, exiting" action="exit"
+bash ../Openshift-EE/utils/error_handler ${retcode} msg="Unable to find litmus test runner pod, exiting" action="exit"
 
 ## Wait till the ansibletest container terminates && also confirm job completion status. This is done to ensure
 ## that execution of auxiliary containers such as loggers is completed. Getting the ansibletest ccontainer to completed state 
@@ -30,13 +36,16 @@ jobStateCmd="kubectl get pod ${litmus_pod} --no-headers -n litmus -o custom-colu
 
 while true; do
   cstate=$(eval ${containerStateCmd}); rc=$?
-  if [[ $rc -eq 0 && ! -z $cstate ]]; then
-    if [[ ! $cstate =~ 'terminated' ]]; then
-      sleep 10
-    else break;
+  if [[ $rc -eq 0 && ! $cstate ]]; then
+    sleep 10
+    else if [[ $rc -eq 0 && ! -z $cstate ]]; then
+      if [[ ! $cstate =~ 'terminated' ]]; then
+        sleep 10
+      else break;
+      fi
+    else
+      echo "unable to get litmus container status"; exit 1
     fi
-  else
-    echo "unable to get litmus container status"; exit 1
   fi
 done
 
@@ -52,8 +61,6 @@ while true; do
   fi
 done
 echo "Litmus test run Job has completed"
-
-${utils_path}/task_delimiter;
 
 echo "Dumping Litmus test pod logs for debug"; echo ""
 kubectl logs $litmus_pod -n litmus -c ansibletest
